# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/ADV7511_HDMI_OUT/ADV7511_HDMI_OUT.cache/wt [current_project]
set_property parent.project_path G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/ADV7511_HDMI_OUT/ADV7511_HDMI_OUT.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/IPSRC/sccb_control.v
  G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/IPSRC/I2C_OV7670_RGB565_Config.v
  G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/IPSRC/hdmi_ddr_output.v
  G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/IPSRC/convert_444_422.v
  G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/IPSRC/colour_space_conversion.v
  G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/IPSRC/sccb.v
  G:/BaiduYunDownload/CH28/ip_repo/ADV7511_HDMI_OUT/IPSRC/hdmi_display.v
}
synth_design -top hdmi_display -part xc7z010clg400-2
write_checkpoint -noxdef hdmi_display.dcp
catch { report_utilization -file hdmi_display_utilization_synth.rpt -pb hdmi_display_utilization_synth.pb }
